version: '3'

services:
    nginx:
        container_name: nginx
        depends_on:
            - postgres
            - backend
        build:
            context: ./nginx
        networks:
            - internal
        volumes:
            - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx/conf
        ports:
            - 8000:8000

    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
            POSTGRES_DATABASE: postgres

    backend:
        build: ./backend
        container_name: backend
        restart: always
        volumes: 
            - ./backend:/srv
        links:
            - postgres
        depends_on: 
            - postgres
        networks:
            - internal
        ports:
            - 3333:3333
        expose:
            - 3333
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=mysecretpassword

networks:
    internal:
        driver: bridge
