version: '3'

services:
    backend:
        build: ./backend
        container_name: backend
        restart: always
        volumes:
            - ./backend:/srv
        networks:
            - internal
        expose:
            - 3333
        ports:
            - 3333:3333

    frontend:
        build: ./frontend/lead2be-front
        container_name: frontend
        restart: always
        networks:
            - internal
        ports:
            - 8080:80
        expose:
            - 80
networks:
    internal:
        driver: bridge
